theme: jekyll-theme-architect
title: Smart Repository
description: Open-source Digital Asset Management System for Institutional Repositories
baseurl: "/smart-repository"
url: "https://carvingit.github.io"

exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - yarn.lock
  - composer.json
  - composer.lock
  - artisan
  - phpunit.xml
  - webpack.mix.js
  - app
  - bootstrap
  - config
  - database
  - public
  - resources
  - routes
  - storage
  - tests
  - .env
  - .env.example
  - .env.testing
  - .env_saml
  - server.php
  - id
  - re-repos-env.unknown
